### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by danny007in** [nihalgonsalves/esbuild-plugin-browserslist#1]
```js
'use strict'

const browserslist = require('browserslist')
const {
  resolveToEsbuildTarget
} = require('esbuild-plugin-browserslist')

const target = resolveToEsbuildTarget(
  browserslist('default', {
    printUnknownTargets: false
  })
)

console.log(target)

```

```bash
C:\wamp64\www\AdminLTE-ts\node_modules\browserslist\index.js:1179
        throw unknownQuery(name)
        ^
Error [BrowserslistError]: Unknown browser query `default`. Maybe you are using old Browserslist or made typo in query.
    at unknownQuery (C:\wamp64\www\AdminLTE-ts\node_modules\browserslist\index.js:285:10)
    at Function.select (C:\wamp64\www\AdminLTE-ts\node_modules\browserslist\index.js:1179:15)
    at C:\wamp64\www\AdminLTE-ts\node_modules\browserslist\index.js:336:33
    at Array.reduce (<anonymous>)
    at resolve (C:\wamp64\www\AdminLTE-ts\node_modules\browserslist\index.js:318:18)
    at browserslist (C:\wamp64\www\AdminLTE-ts\node_modules\browserslist\index.js:444:21)
    at Object.<anonymous> (C:\wamp64\www\AdminLTE-ts\build\config\esbuild.config.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  browserslist: true
}
```

**Comment by nihalgonsalves** [comment]
That's an error from the `browserslist` query you're using, try `defaults` instead, i.e.:

```ts
const target = resolveToEsbuildTarget(
  browserslist('default', {
    printUnknownTargets: false
  })
)
```

**Comment by nihalgonsalves** [comment]
Ah I see, there was a typo in the README, I've fixed it :)
